import React, { useState } from 'react'
import { withRouter, Route, Redirect, Switch } from 'react-router-dom'

import LoginPage from '../LoginPage'
import ChatRoom from '../ChatRoom'

import useControlledInput from '../../customHooks/useControlledInput'

function App(props) {
  const { history } = props

  // Error message state
  const [errorMessage, setErrorMessage] = useState('')

  // Username state for Login form
  const [username, setUsername, isUsernameValid] = useControlledInput()
  const [isUsernameSubmitted, setIsUsernameSubmitted] = useState(false)

  function onUsernameChange(event) {
    setUsername(event.target.value)
  }

  function onUsernameSubmit(event) {
    event.preventDefault()
    if (!isUsernameValid) return

    setIsUsernameSubmitted(true)

    // If user joining new chat room
    if (history.location.pathname === '/') {
      (async () => {
        try {
          // Fetching room ID generated by server
          const response = await fetch('/api/generateRoomId')

          // If success, then redirecting user to the newly created room
          if (response.ok) {
            const newRoomId = await response.text()
            history.push(`/rooms/${newRoomId}`)

            setErrorMessage('')
          } else {
            setErrorMessage('Error :( Try to reload page!')
          }
        } catch (error) {
          setErrorMessage(`Internal server error: ${error}`)
        }
      })()
    }
  }

  const loginPageProps = {
    username,
    isUsernameValid,
    onChange: onUsernameChange,
    onSubmit: onUsernameSubmit,
  }

  return (
    <div className="column app">
      {/* Render error if any */}
      {errorMessage && <div className="row error">{errorMessage}</div>}

      <Switch>
        <Route
          exact
          path="/"
          render={() => <LoginPage {...loginPageProps} />}
        />

        {/* If user connected via link with room ID, then rendering Login page */}
        {/* If it is a newly created room, then just render it */}
        <Route
          path="/rooms/:roomId"
          render={properties => (isUsernameSubmitted ? <ChatRoom {...properties} username={username} /> : <LoginPage {...loginPageProps} />)}
        />

        {/* Default route */}
        <Route
          path="*"
          render={() => <Redirect to="/" />}
        />
      </Switch>
    </div>
  )
}

export default withRouter(App)
